{
  "message": "object 'img_array' not found",
  "traceback": ["keras_array(x)", "py_resolve_dots(list(...))", "generator$flow(x = keras_array(x), y = keras_array(y), batch_size = as.integer(batch_size), \n    shuffle = shuffle, seed = as_nullable_integer(seed), save_to_dir = normalize_path(save_to_dir), \n    save_prefix = save_prefix, save_format = save_format)", "flow_images_from_data(img_array, generator = datagen, batch_size = 1)", "eval(ei, envir)", "eval(ei, envir)", "withVisible(eval(ei, envir))", "source(file = file, local = envir, echo = echo, encoding = encoding)", "withCallingHandlers({\n    source(file = file, local = envir, echo = echo, encoding = encoding)\n    write_run_property(\"completed\", TRUE)\n}, error = function(e) {\n    write_run_metadata(\"error\", list(message = e$message, traceback = capture_stacktrace(sys.calls())))\n    stop(e)\n})", "force(expr)", "tryCatch({\n    tfruns::training_run(file = deploy$entrypoint, context = deploy$context, \n        config = \"cloudml\", flags = deploy$overlay, encoding = \"UTF-8\", \n        echo = TRUE, view = FALSE, run_dir = run_dir)\n}, error = function(e) {\n    training_error <<- e\n})"]
}
